# Generated by Django 4.2.10 on 2024-03-28 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSubscription', models.TextField(choices=[('Free', 'FREE'), ('Basic', 'BASIC'), ('Pro', 'PRO')], default='Free')),
                ('numEvents', models.PositiveIntegerField(default=1)),
                ('canEditEvent', models.BooleanField(default=False)),
                ('canSendNotifications', models.BooleanField(default=False)),
                ('canHaveRecurrentEvents', models.BooleanField(default=False)),
                ('canHaveOustandingEvents', models.BooleanField(default=False)),
                ('canHaveRating', models.BooleanField(default=False)),
                ('ocialClientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OcialClientId', to='user.ocialclient')),
            ],
        ),
    ]
