# Generated by Django 4.2.10 on 2024-03-26 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ocialClientId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='OcialClientId', to='user.ocialclient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='numEvents',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='typeSubscription',
            field=models.TextField(choices=[('Free', 'FREE'), ('Basic', 'BASIC'), ('Pro', 'PRO')], default='Free'),
        ),
    ]
