# Generated by Django 4.2.10 on 2024-03-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_numevents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='numEvents',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
