# Generated by Django 4.2.10 on 2024-03-17 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_ocialuser_typesfaveventtype'),
        ('subscription', '0003_alter_subscription_numevents'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ocialClientId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='OcialClientId', to='user.ocialclient'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='typeSubscription',
            field=models.TextField(choices=[('0', 'FREE'), ('1', 'BASIC'), ('2', 'PRO')]),
        ),
    ]
