# Generated by Django 4.2.10 on 2024-03-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_ocialclientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='typeSubscription',
            field=models.TextField(choices=[('Free', 'FREE'), ('Basic', 'BASIC'), ('Pro', 'PRO')], default='Free'),
        ),
    ]
