# Generated by Django 4.2.10 on 2024-03-10 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="chat",
            new_name="chatId",
        ),
    ]
