# Generated by Django 4.2.10 on 2024-03-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.TextField(choices=[(0, 'SPORTS'), (1, 'MUSIC'), (2, 'MARKETS'), (3, 'RELAX_ACTIVITIES'), (4, 'LIVE_CONCERT')], default=0),
        ),
    ]
