# Generated by Django 4.2.10 on 2024-03-24 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("images", "0002_alter_image_image"),
        ("user", "0001_initial"),
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Like",
                to="user.ocialuser",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="EventImage",
                to="images.image",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="ocialClient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="OcialClient",
                to="user.ocialclient",
            ),
        ),
    ]
