# Generated by Django 4.2.10 on 2024-03-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
        ("event", "0002_remove_event_blurhash_remove_event_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="EventImage",
                to="images.image",
            ),
        ),
    ]
