# Generated by Django 4.2.10 on 2024-03-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0002_alter_event_category"),
        ("event", "0002_rename_event_event_description"),
    ]

    operations = []
