# Generated by Django 4.2.10 on 2024-03-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("image", models.ImageField(upload_to="media/")),
                ("blurhash", models.TextField()),
            ],
        ),
    ]
