# Generated by Django 4.2.10 on 2024-02-24 11:41

from django.db import migrations
import localflavor.es.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocialuser',
            name='dni',
            field=localflavor.es.models.ESIdentityCardNumberField(blank=True, max_length=9, null=True),
        ),
    ]
