# Generated by Django 4.2.10 on 2024-03-02 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_ocialuser_lastknowloclat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocialuser',
            name='typesfavEventType',
            field=models.TextField(choices=[('0', 'Sports'), ('1', 'Music'), ('2', 'Markets'), ('3', 'Relax activities'), ('4', 'Live concerts')], default='0'),
        ),
    ]
