name: Lint

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          show-progress: false
          fetch-depth: 0

      - name: Lint
        uses: psf/black@stable
        with:
            options: "-t py312"

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autoflake

      - name: Remove unused variables
        run: autoflake --recursive --in-place --exclude=settings.py  --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables .

      # In case other workflows pushed changes before this one
      - name: Pull new changes
        run: |
          git config pull.rebase true
          git config rebase.autoStash true
          git pull

      - name: Push formatted code
        uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "style: lint code"
