name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Lint
        uses: psf/black@stable
        with:
          jupyter: false
          options: "--check --verbose"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12  # ajusta esto según tus necesidades
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install autoflake
      - name: Remove unused variables
        run: autoflake --recursive --in-place --exclude=settings.py  --remove-all-unused-imports --remove-duplicate-keys --remove-unused-variables .
      - name: Git config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Push formatted code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style: lint code"